### ISSUE TITLE
Temática/Historia

### ISSUE THREAD

**Issue by SergioSanzSacristan** [TecnologiaVideojuegos/proyecto-videojuego-team3#1]
Como historia, una idea que se me ha ocurrido, podría ser que según el personaje vaya avanzando niveles o vaya consiguiendo logros, en vez de conseguir experiencia, consiguiese créditos llegando a ser el máximo 240 que sería cuando el personaje ha pasado todos los niveles. También siendo bosses, o personajes a batir algunos que representen ciertas asignaturas que suelen ser mas complicadas a lo largo de la carrera. Podéis aportar mas ideas que aumenten este desarrollo o nuevas.

**Comment by ghost** [comment]
La primera idea que se me ocurre:
Puesto que me gusta la idea los créditos, se me ocurre una historia graciosa. Podríamos contar la historia de un niñ@, que quiere comprarse una chocolatina (por ejemplo), pero no tiene dinero. Entonces, se pierde por la ciudad en busca de unas moneditas y claro, para conseguirlas va a pasar una aventura importante. El objetivo final sería la chocolatina. Los enemigos cualquier persona a la que la pueda robar o engañar de alguna forma.

**Comment by Briandacr** [comment]
Hasta que tome forma alguna yo doy ideas.
Nuestro personaje es infectado el principio del juego (por el malvado de la historia). Este tiene que ir recorriendo las plataformas hasta el hospital mientras va recogiendo medicamentos para seguir vivo. De vez en cuando metemos secuaces del malo y, a la entrada del hospital al malo principal.
Pondremos contador para que sea un juego que haya que pasarse rápido.

**Comment by rafaelmaderuelo** [comment]
Se me ha ocurrido un videojuego "dual", tiene dos personajes que vas jugando sus historias simultaneamente hasta llegar a un nivel final en el que tengas que elegir a cual de los dos salvar y que tenga dos variantes la historia, depende de la que elijas; las dos malas o las dos buenas o una buena y una mala. Esta idea se puede implementar en casi cualquier historia.

**Comment by ghost** [comment]
OTRA IDEA!
Un científico/a (loco o no), derrama uno de sus experimentos lo que resulta en un accidente fatal. Él experimentaba con formas de vida y al derramas lo que fuese, éstas mutan por todo el laboratorio y él tiene que ir limpiando todo el estropicio con los artilugios que se va encontrando por el laboratorio (que serían las armas). El jefe final por ejemplo sería que estaba trabajando en un clon de sí mismo y éste se ha escapado. Todo (o casi todo) transcurriría  en el laboratorio así que la línea temporal no es importante. Pero si queremos armas chulas, pues sería algo futurista.

**Comment by ghost** [comment]
MAS Y ESTA ES BONITA
Empieza una escena de un chico/a sufriendo acoso en el colegio/instituto, llega a casa y al dormir tiene un sueño consigo mismo. El sueño/pesadilla tiene a todos sus miedos personificados y él tiene que luchar contra ellos y el nivel final es una representación de su matón/a. Si lo complicamos más, el protagonista en el sueño puede luchar contra sus miedos y acabar con ellos o unirse con ellos, haciéndose más fuerte pero claro, de alguna forma peor persona. Todo esto ocurre en su cabeza así que podemos hacer lo que queramos con la temática.

**Comment by Briandacr** [comment]
El científico:
Nuestro prota crea un clon y estan trabajando en el laboratorio. La lían con una sustancia X y terminan infectados y con medio laboratorio lleno de bichos raros. Estos tienen que ir a contrarreloj a por la cura y, al final, matarse por ella.

**Comment by ghost** [comment]
Sobre el científico:
Necesitamos un poco de trasfondo, que haya un poco de empatización con el protagonista. Lo que hemos hablado antes en clase, de que haya un científico y un aprendiz me parece buena idea. Los dos están trabajando juntos y se les derrama algo que provoca un virus que les infecta a los dos. Ambos se separan para buscar la cura, y mientras se va representando (mediante flashbacks o eventos, llamadas de teléfono...) las historias personales de cada personaje. Es decir, el científico tiene mujer e hijos y le recriminaban el poco tiempo que pasaba con ellos; y el aprendiz tiene una novia y está suuuper enamorado y está trabajando en el laboratorio para ganar dinero para su madre. Los enemigos serían mutaciones (babosas, bichos feos en general). Entonces vas jugando con cada uno un poco hasta que ambos coinciden en la sala, y sólo hay una cura. Ahí, eliges con quien quieres pelear, si con el aprendiz o con el científico. Ambos pelean a muerte (o al menos hasta que uno tenga la cura) y fin. Triste lloramos porque nos molesta que uno tenga que morir sí o sí pero nos hemos divertido.
