### ISSUE TITLE
Reparto de tareas

### ISSUE THREAD

**Issue by Briandacr** [TecnologiaVideojuegos/proyecto-videojuego-team3#10]
Vamos a poner aquí las tareas de las que se ocupa (principalmente) cada uno (por tenerlo en Github y en limpio). Todos vamos a colaborar pero habrá un encargado de cada una.

**Comment by rafaelmaderuelo** [comment]
Yo me propongo como creador de los mapas y si consigo aprender algo del maravilloso slick2d pues ayudo en la programación.

**Comment by SergioSanzSacristan** [comment]
Yo ya me defiendo con el slick2D, lo único, que necesito los mapas y los sprites de los personajes para poder ir avanzando. Los que estáis con mapas y sprites por favor centraros en ello, ya que, sin ellos no se puede avanzar en la programación.

**Comment by ghost** [comment]
Yo sigo con los sprites de los personajes/objetos y a ver si con suerte (o tiempo) aprendo algo de programación también
