### ISSUE TITLE
PPT 

### ISSUE THREAD

**Issue by Briandacr** [TecnologiaVideojuegos/proyecto-videojuego-team3#11]

**Comment by Briandacr** [comment]
[DangerFlask.pptx](https://github.com/TecnologiaVideojuegos/proyecto-videojuego-team3/files/1985508/DangerFlask.pptx)

**Comment by ghost** [comment]
Le añadí la diapositiva que habla de la función de los niveles. Retoque unas cosillas (como sugerencia, se pueden volver a dejar como antes). <333
[DangerFlask.pptx](https://github.com/TecnologiaVideojuegos/proyecto-videojuego-team3/files/1989368/DangerFlask.pptx)

**Comment by Briandacr** [comment]
Lo he decorado un poco y le he añadido una última diapositiva, a ver que os parece.
En el periódico, dejé la misma letra pero puse un par de palabras en rojo, para que destaquen un poco mas, pero si no os convence cogemos la otra.
[DangerFlask.pptx](https://github.com/TecnologiaVideojuegos/proyecto-videojuego-team3/files/1990597/DangerFlask.pptx)

**Comment by Briandacr** [comment]
En cuanto al orden, yo estoy muy incómoda hablando en público así que, si no tenéis preferencia, me gustaría hablar de los primeros y si podemos ser el primer grupo mejor!

Para la diapositiva de diálogos los he puesto según esta escena:
Empezamos el día que van a probar la cura (esta no ha fallado NINGUNA prueba. Así que, para ello, infectan a nuestro bicho mas grande QUE AUN NO ESTABA INFECTADO. Total, que la reacción va mal y el bicho se vuelve loco. Yo he pensado que lo suyo sería que les atacase / mordiese en lugar de que la enfermedad pase a estado gas. Entonces, Julián se iría a cerrar el laboratorio (para que el mono no se escape) y el otro a la caza del mono (que es cuando se da cuenta de que los bichos también han sido mordidos / han reaccionado mal también (no hace falta que demos todos los detalles). 

La parte de historia la llevo bien pero la de descripción de personajes (si os queréis explayar) pues no mucho. Lo mismo de la parte musical.

Otra opción: Podemos hablar todos en plan dialogo a la vez, no por turnos. (Esta es mi favorita) 

Confirmad!

**Comment by ghost** [comment]
Me parece correcta la escena: los muerden y uno activa el sistema de emergencia. Yo puedo explicar en qué consistirán los niveles y el tema de la música (aunque es solo una frase).
