### ISSUE TITLE
Personajes

### ISSUE THREAD

**Issue by Briandacr** [TecnologiaVideojuegos/proyecto-videojuego-team3#2]
Aquí vamos a tratar el número de personajes, tipo, habilidades...
Se ha mencionado usar asignaturas difíciles como enemigo. ¿Que os parece?

**Comment by SergioSanzSacristan** [comment]
Por lo tanto según la historia que hemos decidido los personajes principales serían un científico y un aprendiz. Siendo estos los dos únicos personajes ahora habría que decidir el trasfondo de la historia y diseño de cada uno de ellos.

**Comment by Briandacr** [comment]
Aquí pongo una lista de nombres que han salido en clase: 
Julián Ponzoña, Bacillus Vlad, Gradilla, Erlenmeyer, Kitasato

**Comment by rafaelmaderuelo** [comment]
Mis propuestas:
Samuel Tó,  Simeón Tolomeo ó Zacarías Lacura.
