### ISSUE TITLE
Sprites, fondos y más.

### ISSUE THREAD

**Issue by rafaelmaderuelo** [TecnologiaVideojuegos/proyecto-videojuego-team3#3]

**Comment by Briandacr** [comment]
¿Vamos a buscar un fondo ya diseñado o vamos a crearlo?

**Comment by rafaelmaderuelo** [comment]
Yo buscaría los fondos y los personajes los podemos hacer nosotros a ver como quedan.

**Comment by rafaelmaderuelo** [comment]
Fondos, decorados y sprites
En este juego lo que se dice fondos no va a tener, si no que tendrá plantillas base que enfoquen la temática del juego; en este caso serán emplazamientos como laboratorios, zonas de alta seguridad o salas de investigación, estos estarán creados con herramientas como TILED a base de tiles - “baldosas”-, plantillas con objetos básicos para que construyas tu mapa o nivel.                                                                  En cuanto a los decorados, estarán dentro de los baremos de lo que es un laboratorio antes y después de un mini apocalipsis, intentando representarlo de la forma más realista posible (dentro de las posibilidades que tenemos), adoptando tonalidades más oscuras e intrigantes según va transcurriendo el juego. Los sprites serán en la medida de lo posible lo más detallistas posibles, pero siguiendo un estilo por decirlo así a la antigua usanza, se desarrollarán por ejemplo en el programa PISKEL.

**Comment by rafaelmaderuelo** [comment]
![imagen_mapa_ejemplo](https://user-images.githubusercontent.com/37187051/38635583-209cef1a-3dc6-11e8-9084-e632a435f072.PNG)

para añadir en el documento como ejemplo!!

**Comment by rafaelmaderuelo** [comment]
![imagen_personaje_ejemplo](https://user-images.githubusercontent.com/37187051/38635951-340a587a-3dc7-11e8-9fa4-b65f82cd90e8.PNG)

para añadir en el documento como ejemplo!!
