### ISSUE TITLE
JUGABILIDAD

### ISSUE THREAD

**Issue by ghost** [TecnologiaVideojuegos/proyecto-videojuego-team3#4]
Chicxs, tenemos que hablar qué modo de juego va a tener nuestro videojuego. ¿Queremos que haya lucha? (Por favor, sí) ¿Queremos que vaya rápido? ¿Muchos niveles? ¿Un sólo mapa? ...

**Comment by Briandacr** [comment]
Creo que un juego de plataformas, sin mucho detalle de peleas es entretenido y no será demasiado complicado. Serían muchos niveles que den la sensación de ir seguidos.

**Comment by rafaelmaderuelo** [comment]
!!Apoyo la idea de las plataformas¡¡

**Comment by Briandacr** [comment]
Hay que pensar a que nivel de detalle vamos a poner las peleas. En plan disparos, hachas, puñetazos...

**Comment by ghost** [comment]
Me parece guay. Un videojuego de plataformas, con un mapa que fluye con el personaje.

**Comment by SergioSanzSacristan** [comment]
Según va avanzando el juego nos vamos encontrando distintas armas y enemigos sin una gran complejidad de movimientos para no dificultar la programación y el diseño de movimientos de los personajes.
