### ISSUE TITLE
Documento del diseño de videojuego

### ISSUE THREAD

**Issue by SergioSanzSacristan** [TecnologiaVideojuegos/proyecto-videojuego-team3#5]
He subido el documento word del diseño del videojuego. Abro esto para debatir lo que debemos introducir en el documento.

**Comment by rafaelmaderuelo** [comment]
los puntos a tratar primeramente serian:
1. el propósito del juego
2. el tipo de juego y los "feelings"(apariencia y adjetivos globales que describan la historia del juego)
3. el tipo de vista (posicion de la camara)
4. los personajes (se comenta un poco la dualidad de los personajes)
5. la interfaz de usuario (que se ve en la pantalla y enumeración de botones)

**Comment by ghost** [comment]
- PROPÓSITO DEL JUEGO -
El objetivo de nuestros protagonistas es ante todo, sobrevivir al virus. Para ello, tendrán que buscar por un laboratorio lleno de peligros mutantes, la cura.

**Comment by ghost** [comment]
- LOOK AND FEEL (para nada es definitivo) -
Danger Flask (por ejemplo) sería un drama (no se que poner), con una tensión constante y un mapa lleno de colores. Además, aunque haya un poco de comedia, a medida que jugamos empezamos a temer más por la vida de nuestros protagonistas.

**Comment by Briandacr** [comment]
INTRODUCCIÓN -
Nos encontramos en el siglo XXIII. La humanidad se encuentra sobrecogida por una nueva y mortal enfermedad “inserte nombre”. Esta, se ha llevado ya miles de víctimas y va extendiéndose a una velocidad preocupante. Según los estudios, ha brotado en Europa, tal vez en el sur.
Muchos son los científicos que la intentan destruir, pero, por el momento, solo uno ha hecho avances reales.
En un lugar secreto, escondido bajo tierra, se encuentra el enorme laboratorio, dirigido por el exitoso científico Zacarías Lacura. Junto a él, un sobresaliente estudiante busca destacar en este mundo de la mano de un grande, el joven Julián Ponzoña.
Muchos piensan que, los grandes avances de nuestros protagonistas son debidos a sus mentes brillantes y su pasión por la ciencia, nada más lejos de la realidad.
Leopoldo, primogénito de Zacarías, sobrevive día a día a esta terrible enfermedad. También lo hace Briadna, joven compañera del señor Julián.
Entre sus diversos estudios, observan las diferentes reacciones de la enfermedad en especies animales. Estos están acomodados en una especie de vitrinas de exposición, con unos viales por donde prueban las distintas soluciones.  Por el momento, sus logros han conseguido mantenerlos con vida, pero a duras penas pueden levantarse.
Pero ese particular día, la tensión por encontrar la cura ha hecho mella en nuestros protagonistas y, por un pequeño error, podrían perder la vida antes de lo esperado.

Si se os ocurre mas, adelante.

**Comment by rafaelmaderuelo** [comment]
Solo cambiaría esa frase:
Muchos son los científicos que la intentan contener y en el mejor de los casos erradicarla pero por el momento, solo uno ha hecho avances reales.

**Comment by rafaelmaderuelo** [comment]
Puntos ha tratar:
El tipo de vista de la cámara podría ser desde arriba (tipo pokemon).
La música de que tipo va a ser. (no hace falta poner la música en concreto que se utilizara) 
Describir a los personajes; explicar la mecánica de dualidad entre personajes a controlar.
Los controles que tendrá el juego (las teclas para cada cosa)
Hablar de los niveles y de los decorados
Y para poner al principio del diseño: ¿que es lo diferente del juego? No hay un final feliz como en la mayoría de los casos.

**Comment by SergioSanzSacristan** [comment]
En cuanto al tipo de vista de la cámara optaría a que fuese desde arriba ya que en cuanto a posibilidades para mapas es mucho mayor de esta forma.

**Comment by rafaelmaderuelo** [comment]
Boceto: Apartado Música.
La música en este juego va a ser un pilar fundamental, que te sobrecogerá o te emocionará según los acontecimientos. Pero en principio la música será dramática a la vez que imponente en las fases de pelea y en el trascurso del juego ira cambiando hacia música más tranquila en las zonas donde solamente se tenga que andar hacia otra fase. +
+frase que explique el genero musical característico del juego.

**Comment by Briandacr** [comment]
Interfaz de usuario.
Durante el juego, el usuario tendrá por pantalla los diversos mapas del juego. 
Abajo en el centro, podrá ver el inventario de nuestro personaje donde se nos informa de las armas y diversos objetos utilizables o no durante el juego.
Al ser un juego desarrollado por ordenador, los controles vendran en una pequeña indicación al principio del juego, pero sin necesidad de estar en los mapas.

**Comment by Briandacr** [comment]
Chicos, hemos creado este word con las imágenes y los fondos. No me convence mucho la letra.
Echadle un vistazo.
Cambiad lo que queráis pero utilizad las cajas de texto.

[DangerFlask.docx](https://github.com/TecnologiaVideojuegos/proyecto-videojuego-team3/files/1900226/DangerFlask.docx)

**Comment by rafaelmaderuelo** [comment]
[DangerFlask1.docx](https://github.com/TecnologiaVideojuegos/proyecto-videojuego-team3/files/1900289/DangerFlask1.docx)

**Comment by ghost** [comment]
AQUÍ ESTÁ
[DangerFlask.docx](https://github.com/TecnologiaVideojuegos/proyecto-videojuego-team3/files/1900330/DangerFlask.docx)
