### ISSUE TITLE
Detalles del juego

### ISSUE THREAD

**Issue by Briandacr** [TecnologiaVideojuegos/proyecto-videojuego-team3#9]
He escrito las ideas en otro issue, pero dado que era mas para el DOC pues mejor que sigamos por aquí.
Como fin del juego, me gustaría poner una trampa. Mi idea es que, derrotes o no al mono le plantemos un Game Over porque le mata la enfermedad si o si.
En la última pantalla de cada uno (o solo en uno), un poco antes de que vaya a cruzar la puerta para el jefe final, podemos poner algo como un resplandor al otro lado de la sala (que se vea pero que no cante mucho). 
La historia podría ser que un trozo de pared se ha derribado, dando acceso justo al armario donde está la cura, por lo que puedes acceder a ella, salvas el lab, a tu compañero y a toda la tierra.
Ahora haré el diseño del edificio si os convence la idea.

**Comment by ghost** [comment]
Bufff duro final, pero al menos es un idea. Tenemos que retocar el tema del final la verdad.
